### ISSUE TITLE
Installation problem on the Jetson TX1

### ISSUE THREAD

**Issue by mastrcheif** [torch/cutorch#446] opened 2016-07-15 12:59 UTC
I try to install the current cutorch with 'luarocks install cutorch' to test out the fp16 implementation, but I get stuck at this point:

[ 65%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTypeUtils.cu.o
Killed
CMake Error at THC_generated_THCTensorMathPointwise.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-8521/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPointwise.cu.o

make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMathPointwise.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

I also have the current Jetpack(v2.2) installed with 64bit support

**Comment by mastrcheif** [comment] 2016-07-15 14:36
I cloned the repo and went to the 'cutorch-template-types' branch, which says, that it also has the fp16 support and yeah during installation it detected the cuda support for fp16 and marked it for compilation and the install process worked without trouble.
The problem now is, that it does not work create a HalfTensor with 

```
require 'cutorch'
t = torch.CudaHalfTensor
```

**Comment by mastrcheif** [comment] 2016-07-30 18:34
I was looking forward to this new PR where fp16 integrations seemed to be complete and I can install it on my desktop pc with a gtx 960(cuda 7.5 and cudnn 5.0)
But I am still struggling to get it to run on the Jetson TX1(cuda 7.0 and cudnn 5.0).
This is the newest error while trying to install cutorch. Hope anybody can help me with that.

`[ 47%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMasked.cu.o
Killed
CMake Error at THC_generated_THCTensorMathCompareT.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-5834/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathCompareT.cu.o
`

**Comment by soumith** [comment] 2016-07-31 00:10
@mastrcheif Killed just means that the board went Out of Memory on you while compiling...
It's going to be really slow, but you might have to change this line:
https://github.com/torch/cutorch/blob/master/rocks/cutorch-scm-1.rockspec#L23

to

```bash
cmake -E make_directory build && cd build && cmake .. -DLUALIB=$(LUALIB) -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(LUA_BINDIR)/.." -DCMAKE_INSTALL_PREFIX="$(PREFIX)" && $(MAKE) install
```

i.e. you will have to remove the multi-threaded compilation and see if that will be enough...

**Comment by mastrcheif** [comment] 2016-07-31 20:02
thank you @soumith, installation takes now around 1 hour but it can install it.

But sill I don't get the CudaHalfTensor  detected on the TX1 when I require cutorch for some reason.

**Comment by soumith** [comment] 2016-08-02 16:06
i'm going to clean up my TX1 and start it, will see how far I'll get now.

**Comment by rossgoodwin** [comment] 2016-08-05 01:33
@soumith I'm having this issue now—did you find a resolution?

**Comment by dusty-nv** [comment] 2016-08-09 15:32
After setting -J1 it compiles, but when requiring cutorch it takes a 4-5 seconds then `cutorch.hasHalf == false`.   When requiring cudnn, error `cudnn/init.lua:40: declaration specifier expected near `'half'`.
This was under Jetpack 2.2.1 / L4T R24.1 aarch64.

**Comment by dusty-nv** [comment] 2016-08-09 17:34
Hmm, I confirmed the header exists on TX1 at:   ` /usr/local/cuda-7.0/include/cuda_fp16.h`

**Comment by soumith** [comment] 2016-08-09 17:57
oh hmm, yea, so if you see the version check, it wants > 7.0, while your CUDA == 7.0.
Any chance you can update your CUDA version?

**Comment by dusty-nv** [comment] 2016-08-09 18:13
For TX1 it's a special version 7.0 of the CUDA toolkit that NVIDIA has backported the 7.5 features relevant to TX1, so there isn't update.   Maybe I try patching the FindCUDA locally.

**Comment by borisfom** [comment] 2016-08-09 19:23
@dusty-nv: there should be no need to simulate higher version. I remember I was having some issues with this particular EXISTS when I introduced extra check for Android. 
I will try compiling on my TX1 today. In the meantime - yes just patch cmake/3.6/Modules/FindCUDA.cmake in your torch distro clone.

**Comment by wickedfoo** [comment] 2016-08-12 22:17
Half support is only compiled into CUDA 7.5+ because the defined type for "half" is different between 7.0 and 7.5.

**Comment by wickedfoo** [comment] 2016-08-12 22:18
(i.e., there is code in use that won't compile for CUDA 7.0 because it is now a struct with a member)

**Comment by borisfom** [comment] 2016-08-12 22:55
@wickedfoo: CUDA 7.0 on TX1 has half backported form 7.5. We have working Caffe training in fp16 on TX1.

**Comment by wickedfoo** [comment] 2016-08-13 16:38
@borisfom is `half` typedef'd to a struct containing a short or to a short? I thought in 7.0 it was typedef'd to a short not a struct, hence the compilation incompatibility.

**Comment by borisfom** [comment] 2016-08-13 22:35
Yes here is how it looks on TX1's version of 7.0:
typedef struct __align__(2) {
   unsigned short x;
} __half;

typedef struct __align__(4) {
   unsigned int x;
} __half2;

#ifndef CUDA_NO_HALF
typedef __half half;
typedef __half2 half2;
#endif /*CUDA_NO_HALF*/

**Comment by borisfom** [comment] 2016-08-13 22:35
Also, 8.0 is coming, to aarch64 as well.

**Comment by borisfom** [comment] 2016-08-15 18:16
Confirmed: I was also able to build it with CUDA 8.0 latest snapshot (8.0.41), here: https://github.com/borisfom/distro.  
If it fails auto-detecting CUDA version (e.g. I had a driver compat issue while building),  you may want to 'export TORCH_CUDA_ARCH_LIST=5.3' to reduce the CUDA compilation part.

**Comment by borisfom** [comment] 2016-08-15 18:19
@wickedfoo: this issue should be fixed here: https://github.com/soumith/cudnn.torch/commit/59ac9afc330e3b848fb204afeb8d6f2835902540

**Comment by cgpadwick** [comment] 2016-08-18 16:16
Hi - I've been following this thread.  I have gotten cutorch to build on the TX1, but now I am stuck on hasHalf = false.  I updated with "luarocks install cutorch".  Should I be pulling a specific version of cutorch perhaps?  or does this grab the latest?

**Comment by soumith** [comment] 2016-08-24 23:56
@borisfom if you have time, can you look into TX1 build. thank you.

**Comment by borisfom** [comment] 2016-08-25 01:00
@soumith: Sure I certainly can! Let me know what your priority here is  : 1) just make it work with cuda 7.0 and 2) getting it work really well with using gcc's __fp16 built-in type and cuda 8.0.

**Comment by soumith** [comment] 2016-08-25 01:04
I think 7.0 is the priority. I've been doing all the type work. After a few more of my pull requests, cutorch will be fully fp16 compatible (i.e. with native fp16 type)

**Comment by borisfom** [comment] 2016-08-26 21:43
@cgpadwick, @soumith: OK I was able to reproduce cutorch.hasHalf == false on TX1+cuda 7.0
Will try to fix initialization.

**Comment by borisfom** [comment] 2016-08-29 19:08
Sumbitted https://github.com/torch/cutorch/pull/488

**Comment by mastrcheif** [comment] 2016-09-01 12:35
Okay I tested it today first with the `luarocks install cutorch` command, which crashed at first and after applying @soumith patch again, which can be found above, **it works now** =)
It shows that it can work with half tensors on the TX1. 
thank you @borisfom and @soumith  for your help

**Comment by cgpadwick** [comment] 2016-09-01 16:23
Works for me too.  thanks!

**Closed** 2016-09-01 19:47 UTC

**Comment by dusty-nv** [comment] 2016-09-14 15:58
Just FYI, yesterday NVIDIA released [https://developer.nvidia.com/embedded/jetpack](JetPack 2.3) for TX1, which includes an upgrade to CUDA Toolkit 8.   When trying it on a pre-release version, cutorch and half FP16 detection seemed to work as expected with CUDA 8.
