### ISSUE TITLE
when I run  the command:  $ luajit -lcutorch -lcunn   then returned Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Alex-zhai** [torch/cutorch#271] opened 2015-10-27 06:25 UTC

**Comment by albanD** [comment] 2015-10-27 10:07
This ticket does not give more information than your previous one (and is a duplicate) ...
Please look at the previous one #270 for instruction to get more information.

**Comment by Alex-zhai** [comment] 2015-10-27 13:12
I sloved it ,because someone else is using the gpu when I running the codes.The ram is not enough so Segmentation fault came.Anyway,thank you guys so much!!!

**Comment by fmassa** [comment] 2015-10-27 13:26
if the problem is solved, can you close the issue then ?

**Closed** 2015-10-27 13:27 UTC

**Comment by atefeh-f** [comment] 2018-04-07 20:10
Hi,
i encounter with the same error and i run command of aldben.( i installed torch and luajit and lua):

gdb luajit
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from luajit...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/luajit
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse

require 'torch'
error loading module 'libpaths' from file '/home/atefe/torch/install/lib/lua/5.2/libpaths.so':
/home/atefe/torch/install/lib/lua/5.2/libpaths.so: undefined symbol: luaL_setfuncs
stack traceback:
[C]: at 0x004525b0
[C]: in function 'require'
/home/atefe/torch/install/share/lua/5.2/paths/init.lua:1: in main chunk
[C]: in function 'require'
/home/atefe/torch/install/share/lua/5.2/torch/init.lua:12: in main chunk
[C]: in function 'require'
stdin:1: in main chunk
[C]: at 0x004044a0
