### ISSUE TITLE
cutorch and cunn not installed but install.sh completed with no error

### ISSUE THREAD

**Issue by santisy** [torch/cutorch#400] opened 2016-05-01 05:06 UTC
Hello!

On Ubuntu 16.04 I have installed nvidia driver and cuda 7.5. `nvcc -V` showed version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```
but when I was installing torch, it seemed that `cutorch` and `cunn` was not installed at all and there was **no error** popped out during installation at all. All the other packages of torch have been installed and function well.
I followed the last post of this [thread](https://groups.google.com/forum/embed/?place=forum/torch7#!topic/torch7/aj6cIPABUOA). But even I removed the added line, nothing changed.

Here is the [install.log](https://github.com/santisy/problem/blob/master/install.log). I just wondering if there is a problem with camke to find cuda.

**Comment by soumith** [comment] 2016-05-01 05:28
hey, you've only posted a partial log of the install, can you post the full log of running install.sh

**Comment by santisy** [comment] 2016-05-01 05:56
@soumith hi! [this](https://github.com/santisy/problem/blob/master/install.log.2) is the full part of messages `install.sh` prints.

**Comment by soumith** [comment] 2016-05-01 06:03
i think the problem is nvcc is not available in your $PATH.
For example, in a terminal if you type: "which nvcc"
then it will return nil.

Can you add your nvcc to $PATH and then run ./install.sh ?
The lines that check for CUDA / NVCC are here:
https://github.com/torch/distro/blob/master/install.sh#L63-L64

**Comment by santisy** [comment] 2016-05-01 06:07
@soumith thanks for reply. however I have added `/usr/local/cuda-7.5/bin` to `PATH` and `which nvcc` prints `/usr/local/cuda-7.5/bin/nvcc` exactly the path I have added

**Comment by santisy** [comment] 2016-05-01 08:14
@soumith Hi soumith! I have installed successfully the rest cu* things. I just remove the torch and install it again, it works. And I also encountered the problem '‘memcpy’ was not declared in this scope' and follow the instruction [here](https://github.com/torch/torch7/issues/635). Instead of just adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")` to the `CMakeLists.txt` at the root, I have to add to every `CMakeLists.txt` in cu* folders just as the link suggests. Till now all seems to work fine!

**Comment by soumith** [comment] 2016-06-06 06:57
This issues wrt FORCE_INLINES is now fixed in trunk

**Closed by soumith** 2016-06-06 06:57 UTC
