### ISSUE TITLE
Very many warnings

### ISSUE THREAD

**Issue by Atcold** [torch/cutorch#122] opened 2015-03-30 19:11 UTC
Every time I install `cutorch` and `cunn` I get the following warnings
```
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorMath.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorConv.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h
```
Can we simply remove this line `66` instead?
I am not even sure where this file comes from...

**Comment by szagoruyko** [comment] 2015-03-30 19:25
this line is in your cmake installation, commenting it out will only solve the problem locally.

**Comment by Atcold** [comment] 2015-03-30 19:34
I did a fresh install and I would like the "problem" to be solved globally (as if a new user installs Torch for her first time).

**Comment by soumith** [comment] 2015-04-09 16:34
duplicate of #100

**Closed by soumith** 2015-04-09 16:34 UTC

**Comment by Atcold** [comment] 2015-04-09 19:22
My bad, I didn't see https://github.com/torch/cutorch/issues/100

**Comment by hughperkins** [comment] 2015-10-03 14:28
> I did a fresh install and I would like the "problem" to be solved globally (as if a new user installs Torch for her first time).

That's easy enough, since one can just copy/paste the FindCUDA files inside the torch somewhere
