### ISSUE TITLE
Non-contiguous copy fails between two GPUs without p2p access

### ISSUE THREAD

**Issue by dominikgrewe** [torch/cutorch#134] opened 2015-04-10 16:54 UTC
Assuming GPUs 1 and 2 don't support peer-to-peer access, the following code fails:
```lua
require 'cutorch'

x = torch.CudaTensor(10, 10):t()
cutorch.setDevice(2)
y = torch.CudaTensor(10, 10):t()

print('copy')
x:copy(y)
print('sync')
cutorch.synchronize()
print('done')
```

**Comment by shuzi** [comment] 2015-07-07 18:18
@dominikgrewe 

Hello,

is your problem solved?
I run your code, it print out 'copy' and 'sync' and then the program is dead.
the problem seem to be cutorch.synchronize()  ?

**Comment by hughperkins** [comment] 2015-07-08 00:34
@shuzi: Per my understanding, a broken kernel, eg out-of-bounds array access, will cause the commandqueue/stream to crash, but you wont actually notice until you call finish/synchronize.  So, you might think that the problem is in 'sync', but that's just because sync is where it checks for commandqueue errors.

**Comment by wickedfoo** [comment] 2015-12-03 00:49
this should be fixed now with the above diff.

**Closed** 2015-12-03 01:04 UTC
